### ISSUE TITLE
collision option not working as intended

### ISSUE THREAD

**Issue by Symon-S** [trioderegion/warpgate#91] opened 2022-11-10 05:47 UTC
![image](https://user-images.githubusercontent.com/81383360/201010516-029868ba-141d-4eb5-a223-f27f05d9d752.png)
![warpgate](https://user-images.githubusercontent.com/81383360/201010592-f6399f1f-46ef-46bc-a807-2cb4e9c250f7.gif)
![image](https://user-images.githubusercontent.com/81383360/201010684-b4983c1f-e37e-4e22-859c-5614fe4df5ac.png)

**Comment by trioderegion** [comment] 2022-11-10 05:48
Duplicate of #77 . Fix releasing soon.

**Closed by trioderegion** 2022-11-10 05:48 UTC
